name: TypeScript Action Workflow
on:
  workflow_dispatch:

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: softrams/activity@main
        with:
          github-token: ${{ secrets.TOKEN }}
